service: shadow-map

package:
  exclude:
    - ".dist/**"
    - ".cache/**"
    - ".serverless/**"
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'serverless.config.js'
    includeModules: true
  serverless-offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    IPSTACK: d6968220a6aca5a8b00e7f1f7ad1f0c9
    FAUNADB_SECRET: fnADsoSSk_ACC2LzhSq5SXVWGqc9VZye3ARoACIi

functions:
  location:
    handler: src/functions/location.handler
    events:
      - http:
          path: location
          method: get
  migrate:
    handler: src/db/index.migrate
    timeout: 300
    events:
      - http:
          path: migrate
          method: get
