service: shadow-map

package:
  exclude:
    - ".dist/**"
    - ".cache/**"
    - ".serverless/**"
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:service}-${self:custom.stage}
  webpack:
    webpackConfig: 'serverless.config.js'
    includeModules: true
  serverless-offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    IPSTACK: d6968220a6aca5a8b00e7f1f7ad1f0c9
    USERS: ${self:custom.prefix}-users
    APIKEYS: ${self:custom.prefix}-api-keys

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ Users, Arn ]
        - "Fn::GetAtt": [ ApiKeys, Arn ]

resources:
  - ${file(./resources/users.yaml)}
  - ${file(./resources/api-keys.yaml)}

functions:
  location:
    handler: src/functions/location.handler
    events:
      - http:
          path: location
          method: get

  register:
    handler: src/functions/register.handler
    events:
      - http:
          path: register
          method: post

  login:
    handler: src/functions/login.handler
    events:
      - http:
          path: login
          method: post
