Resources:
  ApiKeys:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.prefix}-api-keys
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        - AttributeName: expires
          Enabled: true
