Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.prefix}-users
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
